[package]
name = "generate_mnemonic"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = "2.1.0"
bip32 = {version = "0.5.3", feature = ["alloc"]}
sha2 = "0.10"
ethers = "2.0"
solana-sdk = "2.2.1"
solana-keypair = "2.2.1"
